name: Deploy Website

on:
  workflow_dispatch:
    inputs:
      site_config:
        description: 'Deploy Website'
        required: true
        default: 'ioos.us'
        type: choice
        options:
          - ioos.us
          - comt.ioos.us
          - eds.ioos.us
          - gliders.ioos.us
          - hfradar.ioos.us
          - oa.ioos.us
          - osmc.ioos.us
      site_subdirectory:
        description: 'Deploy to Subdirectory'
        required: false
        default: ''
        type: string

# no permissions by default
permissions: {}

jobs:
  build:
    name: Build ${{ github.event.inputs.site_config }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7.0.0
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set environment variables
        run: |
          echo "SITE_CONFIG=${{ github.event.inputs.site_config }}" >> $GITHUB_ENV
          echo "SITE_SUBDIRECTORY=${{ github.event.inputs.site_subdirectory }}" >> $GITHUB_ENV
          echo "NODE_ENV=production" >> $GITHUB_ENV

      - name: Run the build script
        run: npm run build

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@e1253824e5c10ff9df46874f81ed3ec929e19cfd  # v6.3.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Sync static directory to S3
        run: |
          DESTINATION="s3://ioos-websites/$SITE_CONFIG"
          if [ -n "$SITE_SUBDIRECTORY" ]; then
            DESTINATION="$DESTINATION-$SITE_SUBDIRECTORY"
          fi
          echo "Syncing to $DESTINATION"
          aws s3 sync ./static "$DESTINATION" --delete
